
image:
  repository: leonardomontero/twitter-api-case
  tag: get-tweets-api-12
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 30003
  internalPort: 8081
  targetPort: 8081
  version: v1

env:
- name: LOGSTASH_HOST
  value: 'logstash-logstash'
- name: LOGSTASH_PORT
  value: '5044'
- name: MONGO_HOST
  value: 'mongodb'
- name: MONGO_PORT
  value: '27017'